---
all:
  children:
    k3s_control_plane:
      hosts:
        k3s-cp-1:
          ansible_host: 10.0.10.31
          k3s_role: init
    k3s_workers:
      hosts:
        k3s-worker-1:
          ansible_host: 10.0.10.32
          k3s_role: agent
        k3s-worker-2:
          ansible_host: 10.0.10.42
          k3s_role: agent
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
